spring.config.import=optional:file:.env.properties
spring.application.name=doparation
# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
# Jackson
spring.jackson.mapper.sort-properties-alphabetically=false
# Supabase
supabase.jwt.secret=${SUPABASE_JWT_SECRET}
supabase.url=${SUPABASE_URL}
supabase.service.key=${SUPABASE_SERVICE_KEY}
supabase.jwks.url=${SUPABASE_JWKS_URL}