spring.config.import=optional:file:.env.properties

spring.application.name=gitracker
# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# Supabase
supabase.jwt.secret=${SUPABASE_JWT_SECRET}
supabase.url=${SUPABASE_URL}
supabase.service.key=${SUPABASE_SERVICE_KEY}
supabase.jwks.url=${SUPABASE_JWKS_URL}